name: book-store Client
on:
  push:
    branches: [ main ]
    paths:
      - "client/**"
  pull_request:
    branches: [ main ]
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.2.0
          cache: "npm"
          cache-dependency-path: ./client/package-lock.json

      - name: install
        run: npm install

      - name: typecheck
        run: npm run typecheck

